LinkToStandardLibraries = function()
end

-- Primarily for debugging
-- filter { "toolset:clang", "system:windows" }
--     makesettings {
--         "CC  = " .. '"' .. "clang.exe"   .. '"' .. " --verbose",
--         -- "CXX = " .. '"' .. "clang++.exe" .. '"' .. " --verbose -ferror-limit=0 -fuse-ld=" .. '"' .. "C:/CTools/msys64/clang64/bin/lld-link" .. '"',
--         "CXX = " .. '"' .. "clang++.exe" .. '"' .. " --verbose -ferror-limit=0 -fuse-ld=" .. '"' .. "C:/CTools/msys2/clang64/bin/ld.lld" .. '"',
--         "LD  = " .. '"' .. "ld.lld.exe"  .. '"' .. " --verbose",
--         "AR  = " .. '"' .. "llvm-ar.exe" .. '"' .. " v"
--     }
-- filter {}
-- filter { "toolset:clang", "system:not windows" }
--     makesettings {
--         "CC  = " .. '"' .. "clang"   .. '"' .. " --verbose",
--         "CXX = " .. '"' .. "clang++" .. '"' .. " --verbose -ferror-limit=0 -fuse-ld=" .. '"' .. "/usr/bin/ld.lld" .. '"',
--         "LD  = " .. '"' .. "ld.lld"  .. '"' .. " --verbose",
--         "AR  = " .. '"' .. "llvm-ar" .. '"' .. " v"
--     }
-- filter {}
-- filter { "toolset:gcc" }
--     makesettings {
--         "CC  = " .. '"' .. "gcc" .. '"' .. " --verbose",
--         -- "CXX = " .. '"' .. "g++" .. '"' .. " --verbose -fmax-errors=0 -fuse-ld=" .. '"' .. "lld" .. '"',
--         "CXX = " .. '"' .. "g++" .. '"' .. " --verbose -fmax-errors=0",
--         "LD  = " .. '"' .. "lld"  .. '"' .. " --verbose",
--         "AR  = " .. '"' .. "ar"  .. '"' .. " v"
--     }
-- filter {}
-- filter { "system:windows", "action:gmake" }
-- filter { "system:windows", "action:vs2022" }
-- filter { "system:linux", "action:gmake" }


-- local function add_new_gcc_toolset (name, prefix)
--     local gcc                         = premake.tools.gcc
--     local new_toolset                 = {}  
--     new_toolset.getcflags             = gcc.getcflags
--     new_toolset.getcxxflags           = gcc.getcxxflags
--     new_toolset.getforceincludes      = gcc.getforceincludes
--     new_toolset.getldflags            = gcc.getldflags
--     new_toolset.getcppflags           = gcc.getcppflags
--     new_toolset.getdefines            = gcc.getdefines
--     new_toolset.getincludedirs        = gcc.getincludedirs
--     new_toolset.getLibraryDirectories = gcc.getLibraryDirectories
--     new_toolset.getlinks              = gcc.getlinks
--     new_toolset.getmakesettings       = gcc.getmakesettings
--     new_toolset.toolset_prefix        = prefix
--     function new_toolset.gettoolname (cfg, tool)  
--       if     tool == "cc" then
--         name = new_toolset.toolset_prefix .. "gcc"  
--       elseif tool == "cxx" then
--         name = new_toolset.toolset_prefix .. "g++"
--       elseif tool == "ar" then
--         name = new_toolset.toolset_prefix .. "ar"
--       end
--       return name
--     end  
--     premake.tools[name] = new_toolset
--   end
--   return add_new_gcc_toolset