#version 450 core
layout(local_size_x =   5, local_size_y =   5, local_size_z =   5) in;
layout (binding = 1, rgba32f) writeonly uniform image2D   renderto;
layout (binding = 2)                    uniform sampler2D sim_step_u0;


uniform float ku_dt;
uniform ivec2 ku_simdims;


void main()
{
    ivec2 texelCoord = ivec2(gl_GlobalInvocationID.xy);
    vec2 norm_texcoord = vec2(texelCoord) / vec2(ku_simdims);
    imageStore(renderto, texelCoord, texture(sim_step_u0, norm_texcoord));
    return;
}