#version 450 core
#extension GL_EXT_shader_image_load_formatted : require
layout(local_size_x =   5, local_size_y =   5, local_size_z =   5) in;
layout (binding = 0)          uniform sampler2D sim_velocity_pressure;
layout (binding = 1, rgba32f) writeonly uniform image2D   sim_output;


uniform ivec2 ku_simdims;
vec2 k_unitCoord = vec2(1) / vec2(ku_simdims);


bvec4 isBoundary(ivec2 coords) {
    return bvec4(
        coords.x == 0, 
        coords.y == 0,
        coords.x == (ku_simdims.x - 1),
        coords.y == (ku_simdims.y - 1)
    );
}


void main()
{
    ivec2 texelCoord    = ivec2(gl_GlobalInvocationID.xy);
    vec2  norm_texcoord = vec2(texelCoord) * k_unitCoord;
    const vec4  boundaryMultipliers = vec4(-1.0f, -1.0f, 1.0f, 1.0f);
    const bvec4 boundbits = isBoundary(texelCoord);

    texelCoord += ivec2(boundbits.xy);
    texelCoord -= ivec2(boundbits.zw);
    imageStore(
        sim_output, 
        texelCoord, 
        boundaryMultipliers * texelFetch(sim_velocity_pressure, texelCoord, 0)
    );
    return;
}
